---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: vbox/nginx64
    driver:
      box: xenial64
      provider: virtualbox
 
verifier:
  name: inspec

suites:
  - name: default
