---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: vbox/xenial64
    driver:
      box: xenial64
      provider: virtualbox
  - name: vmware/xenial64
    driver:
      box: xenial64
      provider: vmware_desktop

verifier:
  name: inspec

suites:
  - name: default
